### PR TITLE
fix: memory leak due to Promise.race

### LINKED ISSUE #6: Memory leak in sink
It looks like `sink` has a memory leak. Repro:

```
const fs = require('fs')
const toIterable = require('stream-to-it')
const pipe = require('it-pipe')

async function* run() {
  for (let i = 0; i < 170000; i++) {
    yield Buffer.alloc(4096)
  }
}

(async () => {
  const sink = toIterable.sink(fs.createWriteStream('/some/outfile'))
  await pipe(run(), sink)
  console.log('done')
  await new Promise(resolve => setTimeout(resolve, 1000000));
})()
```

Memory consumption steadily increases until completion and stays at around 800-900 Mb. Total size of those buffers are around 700 Mb. Early diagnostics with chrome webtools point towards the promises and/or the callback hijacking of `stream.end()`.

Found when using the upstream `libp2p-js` with `libp2p-js-tcp`.

node v13.11.0
Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by jacobheun**
Details for why the leak happens are in the issue, https://github.com/alanshaw/stream-to-it/issues/6. This code is heavily influenced by the fix for writeToStream in streaming-iterables but avoids breaking any functionality here.

- Fix leak by removing Promise.race use
- Adds the [leak reproduction code](https://github.com/alanshaw/stream-to-it/issues/6#issue-589555329) to a benchmarks folder. Run instructions leveraging Clinic.js are inline in the file. I can add to the readme if desired.
- Updates deps :)
- Added `package.files` to restrict what gets uploaded (tests were being packaged)
- Travis now runs Node.js `stable`(14) and `lts`(12)

## Clinic.js Reports

I've also listed the IPFS CIDs (linked to the gateway) if you want to peruse in detail.

**After** [bafybeidzy5otcicczh43ifdcg55btdl4q5j75vfolhsygr3oomqjavj6p4](https://gateway.ipfs.io/ipfs/bafybeidzy5otcicczh43ifdcg55btdl4q5j75vfolhsygr3oomqjavj6p4)
image

**Before** [bafybeig3sw5t326is6e7rknf7ena3ffubekperpsdgf2dty7w74pkvmhai](https://gateway.ipfs.io/ipfs/bafybeig3sw5t326is6e7rknf7ena3ffubekperpsdgf2dty7w74pkvmhai)
image

## Package file changes
```sh
$ npm pack --dry-run
npm notice 
npm notice 📦  stream-to-it@0.2.0
npm notice === Tarball Contents === 
npm notice 1.1kB LICENSE     
npm notice 151B  duplex.js   
npm notice 215B  index.js    
npm notice 2.2kB sink.js     
npm notice 494B  source.js   
npm notice 395B  transform.js
npm notice 1.1kB package.json
npm notice 3.4kB README.md
```

fixes https://github.com/alanshaw/stream-to-it/issues/6

### CODE REVIEW

**Comment by jacobheun** [comment]
Tests are failing on node 14, looking into it.

**Comment by jacobheun** [comment]
All fixed. @alanshaw ready for your eyes.

**Comment by jacobheun** [comment]
cc: @achingbrain

File: sink.js [hunk 1]
```diff
@@ -1,112 +1,93 @@
...
+  // Everything is good and we're done writing, end everything
+  if (!error && writable.writable) {
+    writable.end()
+  }
+
+  // Wait until we close or finish. This supports halfClosed streams
+  await waitForDone()
+
+  // Clean up listeners
+  cleanup()
```
Comment (achingbrain) [inline sink.js]: Should this me be more like:

```javascript
try {
  await waitForDone()
} finally {
  // Clean up listeners
  cleanup()
}
```

`waitForDone` assigns `reject` to `errCb` which is invoked in `errorHandler` which will be invoked in turn if there's an `error` event on the writable so we probably still want to remove the listeners?

**Review by achingbrain — CHANGES_REQUESTED** [review]

File: sink.js (hunk 1 above)
Comment (jacobheun) [reply sink.js]: yes, will update

Comment (jacobheun) [reply sink.js]: I've also added writable.end() to the try catch. It **shouldnt** throw, but in the event it does, this will ensure the handlers get cleaned up.

**Review by achingbrain — APPROVED** [review]

**Review by alanshaw — APPROVED** [review]

**Comment by alanshaw** [comment]
❤️ thanks so much for fixing this
